/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ReceiptControllerGetReceipts200Response } from '../models';
/**
 * ReceiptApi - axios parameter creator
 * @export
 */
export const ReceiptApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [namespace] Filter by namespace
         * @param {string} [periodId] Filter by periodId
         * @param {number} [offset] 分页偏移量
         * @param {number} [limit] 每页数量
         * @param {string} [search] 搜索关键字
         * @param {string} [sort] 排序字段，格式如 sort&#x3D;field1:asc,field2:desc（多个排序用逗号分隔，方向为asc或desc）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiptControllerGetReceipts: async (namespace?: string, periodId?: string, offset?: number, limit?: number, search?: string, sort?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/receipts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }

            if (periodId !== undefined) {
                localVarQueryParameter['periodId'] = periodId;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiptControllerMyReceipts: async (type: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('receiptControllerMyReceipts', 'type', type)
            const localVarPath = `/receipts/mine`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReceiptApi - functional programming interface
 * @export
 */
export const ReceiptApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReceiptApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [namespace] Filter by namespace
         * @param {string} [periodId] Filter by periodId
         * @param {number} [offset] 分页偏移量
         * @param {number} [limit] 每页数量
         * @param {string} [search] 搜索关键字
         * @param {string} [sort] 排序字段，格式如 sort&#x3D;field1:asc,field2:desc（多个排序用逗号分隔，方向为asc或desc）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async receiptControllerGetReceipts(namespace?: string, periodId?: string, offset?: number, limit?: number, search?: string, sort?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReceiptControllerGetReceipts200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.receiptControllerGetReceipts(namespace, periodId, offset, limit, search, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReceiptApi.receiptControllerGetReceipts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async receiptControllerMyReceipts(type: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.receiptControllerMyReceipts(type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReceiptApi.receiptControllerMyReceipts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReceiptApi - factory interface
 * @export
 */
export const ReceiptApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReceiptApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [namespace] Filter by namespace
         * @param {string} [periodId] Filter by periodId
         * @param {number} [offset] 分页偏移量
         * @param {number} [limit] 每页数量
         * @param {string} [search] 搜索关键字
         * @param {string} [sort] 排序字段，格式如 sort&#x3D;field1:asc,field2:desc（多个排序用逗号分隔，方向为asc或desc）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiptControllerGetReceipts(namespace?: string, periodId?: string, offset?: number, limit?: number, search?: string, sort?: string, options?: RawAxiosRequestConfig): AxiosPromise<ReceiptControllerGetReceipts200Response> {
            return localVarFp.receiptControllerGetReceipts(namespace, periodId, offset, limit, search, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        receiptControllerMyReceipts(type: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.receiptControllerMyReceipts(type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReceiptApi - interface
 * @export
 * @interface ReceiptApi
 */
export interface ReceiptApiInterface {
    /**
     * 
     * @param {string} [namespace] Filter by namespace
     * @param {string} [periodId] Filter by periodId
     * @param {number} [offset] 分页偏移量
     * @param {number} [limit] 每页数量
     * @param {string} [search] 搜索关键字
     * @param {string} [sort] 排序字段，格式如 sort&#x3D;field1:asc,field2:desc（多个排序用逗号分隔，方向为asc或desc）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptApiInterface
     */
    receiptControllerGetReceipts(namespace?: string, periodId?: string, offset?: number, limit?: number, search?: string, sort?: string, options?: RawAxiosRequestConfig): AxiosPromise<ReceiptControllerGetReceipts200Response>;

    /**
     * 
     * @param {string} type 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptApiInterface
     */
    receiptControllerMyReceipts(type: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * ReceiptApi - object-oriented interface
 * @export
 * @class ReceiptApi
 * @extends {BaseAPI}
 */
export class ReceiptApi extends BaseAPI implements ReceiptApiInterface {
    /**
     * 
     * @param {string} [namespace] Filter by namespace
     * @param {string} [periodId] Filter by periodId
     * @param {number} [offset] 分页偏移量
     * @param {number} [limit] 每页数量
     * @param {string} [search] 搜索关键字
     * @param {string} [sort] 排序字段，格式如 sort&#x3D;field1:asc,field2:desc（多个排序用逗号分隔，方向为asc或desc）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptApi
     */
    public receiptControllerGetReceipts(namespace?: string, periodId?: string, offset?: number, limit?: number, search?: string, sort?: string, options?: RawAxiosRequestConfig) {
        return ReceiptApiFp(this.configuration).receiptControllerGetReceipts(namespace, periodId, offset, limit, search, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} type 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiptApi
     */
    public receiptControllerMyReceipts(type: string, options?: RawAxiosRequestConfig) {
        return ReceiptApiFp(this.configuration).receiptControllerMyReceipts(type, options).then((request) => request(this.axios, this.basePath));
    }
}

