/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LinkWalletDto } from '../models';
/**
 * YoubetApi - axios parameter creator
 * @export
 */
export const YoubetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        youbetControllerGetAllTasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/youbet/all-tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} github 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        youbetControllerGetLinkedWallet: async (github: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'github' is not null or undefined
            assertParamExists('youbetControllerGetLinkedWallet', 'github', github)
            const localVarPath = `/youbet/wallet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (github !== undefined) {
                localVarQueryParameter['github'] = github;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} address 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        youbetControllerGetUserPoints: async (address: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('youbetControllerGetUserPoints', 'address', address)
            const localVarPath = `/youbet/user-points`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (address !== undefined) {
                localVarQueryParameter['address'] = address;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LinkWalletDto} linkWalletDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        youbetControllerLinkWallet: async (linkWalletDto: LinkWalletDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'linkWalletDto' is not null or undefined
            assertParamExists('youbetControllerLinkWallet', 'linkWalletDto', linkWalletDto)
            const localVarPath = `/youbet/wallet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(linkWalletDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * YoubetApi - functional programming interface
 * @export
 */
export const YoubetApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = YoubetApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async youbetControllerGetAllTasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.youbetControllerGetAllTasks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['YoubetApi.youbetControllerGetAllTasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} github 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async youbetControllerGetLinkedWallet(github: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.youbetControllerGetLinkedWallet(github, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['YoubetApi.youbetControllerGetLinkedWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} address 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async youbetControllerGetUserPoints(address: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.youbetControllerGetUserPoints(address, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['YoubetApi.youbetControllerGetUserPoints']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LinkWalletDto} linkWalletDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async youbetControllerLinkWallet(linkWalletDto: LinkWalletDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.youbetControllerLinkWallet(linkWalletDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['YoubetApi.youbetControllerLinkWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * YoubetApi - factory interface
 * @export
 */
export const YoubetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = YoubetApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        youbetControllerGetAllTasks(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.youbetControllerGetAllTasks(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} github 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        youbetControllerGetLinkedWallet(github: string, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.youbetControllerGetLinkedWallet(github, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} address 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        youbetControllerGetUserPoints(address: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.youbetControllerGetUserPoints(address, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LinkWalletDto} linkWalletDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        youbetControllerLinkWallet(linkWalletDto: LinkWalletDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.youbetControllerLinkWallet(linkWalletDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * YoubetApi - interface
 * @export
 * @interface YoubetApi
 */
export interface YoubetApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YoubetApiInterface
     */
    youbetControllerGetAllTasks(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @param {string} github 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YoubetApiInterface
     */
    youbetControllerGetLinkedWallet(github: string, options?: RawAxiosRequestConfig): AxiosPromise<string>;

    /**
     * 
     * @param {string} address 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YoubetApiInterface
     */
    youbetControllerGetUserPoints(address: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @param {LinkWalletDto} linkWalletDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YoubetApiInterface
     */
    youbetControllerLinkWallet(linkWalletDto: LinkWalletDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * YoubetApi - object-oriented interface
 * @export
 * @class YoubetApi
 * @extends {BaseAPI}
 */
export class YoubetApi extends BaseAPI implements YoubetApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YoubetApi
     */
    public youbetControllerGetAllTasks(options?: RawAxiosRequestConfig) {
        return YoubetApiFp(this.configuration).youbetControllerGetAllTasks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} github 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YoubetApi
     */
    public youbetControllerGetLinkedWallet(github: string, options?: RawAxiosRequestConfig) {
        return YoubetApiFp(this.configuration).youbetControllerGetLinkedWallet(github, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} address 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YoubetApi
     */
    public youbetControllerGetUserPoints(address: string, options?: RawAxiosRequestConfig) {
        return YoubetApiFp(this.configuration).youbetControllerGetUserPoints(address, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LinkWalletDto} linkWalletDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof YoubetApi
     */
    public youbetControllerLinkWallet(linkWalletDto: LinkWalletDto, options?: RawAxiosRequestConfig) {
        return YoubetApiFp(this.configuration).youbetControllerLinkWallet(linkWalletDto, options).then((request) => request(this.axios, this.basePath));
    }
}

