/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AchievementDto
 */
export interface AchievementDto {
    /**
     * 
     * @type {string}
     * @memberof AchievementDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AchievementDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AchievementDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof AchievementDto
     */
    'stats': string;
    /**
     * 
     * @type {string}
     * @memberof AchievementDto
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof AchievementDto
     */
    'rarity': string;
    /**
     * 
     * @type {string}
     * @memberof AchievementDto
     */
    'icon'?: string;
}

