/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateIssueDto
 */
export interface CreateIssueDto {
    /**
     * 
     * @type {string}
     * @memberof CreateIssueDto
     */
    'owner': string;
    /**
     * 
     * @type {string}
     * @memberof CreateIssueDto
     */
    'repo': string;
    /**
     * 
     * @type {string}
     * @memberof CreateIssueDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateIssueDto
     */
    'body': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateIssueDto
     */
    'labels': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateIssueDto
     */
    'assignees': Array<string>;
}

