/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ERC20TransferSummaryDto
 */
export interface ERC20TransferSummaryDto {
    /**
     * Transaction hash
     * @type {string}
     * @memberof ERC20TransferSummaryDto
     */
    'hash': string;
    /**
     * Transaction timestamp
     * @type {string}
     * @memberof ERC20TransferSummaryDto
     */
    'timestamp': string;
    /**
     * Block number
     * @type {number}
     * @memberof ERC20TransferSummaryDto
     */
    'blockNumber': number;
    /**
     * Sender address
     * @type {string}
     * @memberof ERC20TransferSummaryDto
     */
    'from': string;
    /**
     * Receiver address
     * @type {string}
     * @memberof ERC20TransferSummaryDto
     */
    'to': string;
}

