/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ERC20StatsFiltersDto } from './erc20-stats-filters-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ERC20TransferSummaryDto } from './erc20-transfer-summary-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TokenValueDto } from './token-value-dto';

/**
 * 
 * @export
 * @interface ERC20StatsDto
 */
export interface ERC20StatsDto {
    /**
     * Applied filters
     * @type {ERC20StatsFiltersDto}
     * @memberof ERC20StatsDto
     */
    'filters': ERC20StatsFiltersDto;
    /**
     * Total number of transfers matching the filters
     * @type {number}
     * @memberof ERC20StatsDto
     */
    'totalTransfers': number;
    /**
     * Value aggregated by token contract
     * @type {Array<TokenValueDto>}
     * @memberof ERC20StatsDto
     */
    'tokenValues': Array<TokenValueDto>;
    /**
     * Number of transfers sent by the from address (only when from filter is applied)
     * @type {number}
     * @memberof ERC20StatsDto
     */
    'sentCount'?: number;
    /**
     * Value sent by token contract (only when from filter is applied)
     * @type {Array<TokenValueDto>}
     * @memberof ERC20StatsDto
     */
    'sentTokenValues'?: Array<TokenValueDto>;
    /**
     * Number of transfers received by the to address (only when to filter is applied)
     * @type {number}
     * @memberof ERC20StatsDto
     */
    'receivedCount'?: number;
    /**
     * Value received by token contract (only when to filter is applied)
     * @type {Array<TokenValueDto>}
     * @memberof ERC20StatsDto
     */
    'receivedTokenValues'?: Array<TokenValueDto>;
    /**
     * Latest transfer matching the filters
     * @type {ERC20TransferSummaryDto}
     * @memberof ERC20StatsDto
     */
    'latestTransfer'?: ERC20TransferSummaryDto;
}

