/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ERC20StatsFiltersDto
 */
export interface ERC20StatsFiltersDto {
    /**
     * Sender address filter
     * @type {string}
     * @memberof ERC20StatsFiltersDto
     */
    'from'?: string;
    /**
     * Receiver address filter
     * @type {string}
     * @memberof ERC20StatsFiltersDto
     */
    'to'?: string;
    /**
     * Start time filter
     * @type {string}
     * @memberof ERC20StatsFiltersDto
     */
    'startTime'?: string;
    /**
     * End time filter
     * @type {string}
     * @memberof ERC20StatsFiltersDto
     */
    'endTime'?: string;
}

