/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GithubPullRequestRefDto
 */
export interface GithubPullRequestRefDto {
    /**
     * 
     * @type {string}
     * @memberof GithubPullRequestRefDto
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubPullRequestRefDto
     */
    'html_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubPullRequestRefDto
     */
    'diff_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubPullRequestRefDto
     */
    'patch_url': string;
}

