/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GithubUserDto
 */
export interface GithubUserDto {
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'login': string;
    /**
     * 
     * @type {number}
     * @memberof GithubUserDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'node_id': string;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'avatar_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'gravatar_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'html_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'type': string;
    /**
     * 
     * @type {boolean}
     * @memberof GithubUserDto
     */
    'site_admin': boolean;
}

