/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubLabelDto } from './github-label-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { GithubMilestoneDto } from './github-milestone-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { GithubPullRequestRefDto } from './github-pull-request-ref-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { GithubUserDto } from './github-user-dto';

/**
 * 
 * @export
 * @interface GithubIssueDto
 */
export interface GithubIssueDto {
    /**
     * 
     * @type {number}
     * @memberof GithubIssueDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'node_id': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'repository_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'labels_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'comments_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'events_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'html_url': string;
    /**
     * 
     * @type {number}
     * @memberof GithubIssueDto
     */
    'number': number;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'body': string;
    /**
     * 
     * @type {GithubUserDto}
     * @memberof GithubIssueDto
     */
    'user': GithubUserDto;
    /**
     * 
     * @type {Array<GithubLabelDto>}
     * @memberof GithubIssueDto
     */
    'labels'?: Array<GithubLabelDto>;
    /**
     * 
     * @type {GithubUserDto}
     * @memberof GithubIssueDto
     */
    'assignee'?: GithubUserDto;
    /**
     * 
     * @type {Array<GithubUserDto>}
     * @memberof GithubIssueDto
     */
    'assignees'?: Array<GithubUserDto>;
    /**
     * 
     * @type {GithubMilestoneDto}
     * @memberof GithubIssueDto
     */
    'milestone'?: GithubMilestoneDto;
    /**
     * 
     * @type {boolean}
     * @memberof GithubIssueDto
     */
    'locked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'active_lock_reason'?: string;
    /**
     * 
     * @type {number}
     * @memberof GithubIssueDto
     */
    'comments': number;
    /**
     * 
     * @type {GithubPullRequestRefDto}
     * @memberof GithubIssueDto
     */
    'pull_request'?: GithubPullRequestRefDto;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'closed_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'updated_at': string;
    /**
     * 
     * @type {GithubUserDto}
     * @memberof GithubIssueDto
     */
    'closed_by'?: GithubUserDto;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'author_association': string;
    /**
     * 
     * @type {string}
     * @memberof GithubIssueDto
     */
    'state_reason'?: string;
}

