/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GithubLabelDto
 */
export interface GithubLabelDto {
    /**
     * 
     * @type {number}
     * @memberof GithubLabelDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GithubLabelDto
     */
    'node_id': string;
    /**
     * 
     * @type {string}
     * @memberof GithubLabelDto
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubLabelDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof GithubLabelDto
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GithubLabelDto
     */
    'color': string;
    /**
     * 
     * @type {boolean}
     * @memberof GithubLabelDto
     */
    'default': boolean;
}

