/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GithubOrganizationDto
 */
export interface GithubOrganizationDto {
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'login': string;
    /**
     * 
     * @type {number}
     * @memberof GithubOrganizationDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'node_id': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'repos_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'events_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'hooks_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'issues_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'members_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'public_members_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'avatar_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubOrganizationDto
     */
    'description': string;
}

