/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GithubUserDto
 */
export interface GithubUserDto {
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'login': string;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'htmlUrl': string;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    'avatarUrl': string;
    /**
     * 
     * @type {number}
     * @memberof GithubUserDto
     */
    'rewards': number;
    /**
     * 
     * @type {string}
     * @memberof GithubUserDto
     */
    '_id': string;
}

