/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubUserDto } from './github-user-dto';

/**
 * 
 * @export
 * @interface GithubRepoDto
 */
export interface GithubRepoDto {
    /**
     * 
     * @type {number}
     * @memberof GithubRepoDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof GithubRepoDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof GithubRepoDto
     */
    'full_name': string;
    /**
     * 
     * @type {boolean}
     * @memberof GithubRepoDto
     */
    'private': boolean;
    /**
     * 
     * @type {GithubUserDto}
     * @memberof GithubRepoDto
     */
    'owner': GithubUserDto;
    /**
     * 
     * @type {string}
     * @memberof GithubRepoDto
     */
    'html_url': string;
    /**
     * 
     * @type {string}
     * @memberof GithubRepoDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof GithubRepoDto
     */
    'created_at': string;
}

