/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { YoubetExtra } from './youbet-extra';

/**
 * 
 * @export
 * @interface ImportProjectDto
 */
export interface ImportProjectDto {
    /**
     * 
     * @type {string}
     * @memberof ImportProjectDto
     */
    'org': string;
    /**
     * 
     * @type {string}
     * @memberof ImportProjectDto
     */
    'project': string;
    /**
     * 
     * @type {string}
     * @memberof ImportProjectDto
     */
    'namespace'?: string;
    /**
     * 
     * @type {object}
     * @memberof ImportProjectDto
     */
    'tutorial': object;
    /**
     * 
     * @type {YoubetExtra}
     * @memberof ImportProjectDto
     */
    'youbetExtra'?: YoubetExtra;
}

