/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Period
 */
export interface Period {
    /**
     * 
     * @type {string}
     * @memberof Period
     */
    'projectId': string;
    /**
     * 
     * @type {string}
     * @memberof Period
     */
    'from': string;
    /**
     * 
     * @type {string}
     * @memberof Period
     */
    'to': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Period
     */
    'pullRequests': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Period
     */
    'commits': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Period
     */
    'contributors': Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Period
     */
    'rewardGranted': boolean;
    /**
     * 
     * @type {string}
     * @memberof Period
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Period
     */
    'updatedAt': string;
}

