/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Period } from './period';
// May contain unused imports in some cases
// @ts-ignore
import type { PeriodControllerGetPeriods200ResponsePagination } from './period-controller-get-periods200-response-pagination';

/**
 * 
 * @export
 * @interface PeriodControllerGetPeriods200Response
 */
export interface PeriodControllerGetPeriods200Response {
    /**
     * 
     * @type {PeriodControllerGetPeriods200ResponsePagination}
     * @memberof PeriodControllerGetPeriods200Response
     */
    'pagination'?: PeriodControllerGetPeriods200ResponsePagination;
    /**
     * 
     * @type {Array<Period>}
     * @memberof PeriodControllerGetPeriods200Response
     */
    'data'?: Array<Period>;
}

