/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubUser } from './github-user';
// May contain unused imports in some cases
// @ts-ignore
import type { Task } from './task';

/**
 * 
 * @export
 * @interface PopulatedTaskApplyDto
 */
export interface PopulatedTaskApplyDto {
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    '_id': string;
    /**
     * 
     * @type {number}
     * @memberof PopulatedTaskApplyDto
     */
    'githubId': number;
    /**
     * 
     * @type {object}
     * @memberof PopulatedTaskApplyDto
     */
    'project': object;
    /**
     * 
     * @type {GithubUser}
     * @memberof PopulatedTaskApplyDto
     */
    'user': GithubUser;
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    'comment': string;
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    'htmlUrl': string;
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    'canceledAt': string;
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    'approvedAt': string;
    /**
     * 
     * @type {object}
     * @memberof PopulatedTaskApplyDto
     */
    'namespace': object;
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    'projectName': string;
    /**
     * 
     * @type {string}
     * @memberof PopulatedTaskApplyDto
     */
    'taskTitle': string;
    /**
     * 
     * @type {Task}
     * @memberof PopulatedTaskApplyDto
     */
    'task': Task;
}

