/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubUser } from './github-user';
// May contain unused imports in some cases
// @ts-ignore
import type { YoubetExtra } from './youbet-extra';

/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    '_id': string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'githubId': number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'fullName': string;
    /**
     * 
     * @type {GithubUser}
     * @memberof Project
     */
    'owner': GithubUser;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'language': string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'openIssuesCount': number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'forksCount': number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'stargazersCount': number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'contributorsCount': number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'htmlUrl': string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'updatedAt': string;
    /**
     * 
     * @type {object}
     * @memberof Project
     */
    'tutorial': object;
    /**
     * 
     * @type {YoubetExtra}
     * @memberof Project
     */
    'youbetExtra': YoubetExtra;
    /**
     * 
     * @type {object}
     * @memberof Project
     */
    'namespace': object;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'approvedAt': string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    'deletedAt': string;
    /**
     * 
     * @type {object}
     * @memberof Project
     */
    'periodicReward': object;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    'priority': number;
}

