/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Project } from './project';
// May contain unused imports in some cases
// @ts-ignore
import type { ReceiptControllerGetReceipts200ResponsePagination } from './receipt-controller-get-receipts200-response-pagination';

/**
 * 
 * @export
 * @interface ProjectControllerGetProjects200Response
 */
export interface ProjectControllerGetProjects200Response {
    /**
     * 
     * @type {ReceiptControllerGetReceipts200ResponsePagination}
     * @memberof ProjectControllerGetProjects200Response
     */
    'pagination'?: ReceiptControllerGetReceipts200ResponsePagination;
    /**
     * 
     * @type {Array<Project>}
     * @memberof ProjectControllerGetProjects200Response
     */
    'data'?: Array<Project>;
}

