/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReceiptDetail } from './receipt-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { ReceiptSource } from './receipt-source';
// May contain unused imports in some cases
// @ts-ignore
import type { ReceiptTransactionInfo } from './receipt-transaction-info';

/**
 * 
 * @export
 * @interface ReceiptDto
 */
export interface ReceiptDto {
    /**
     * 
     * @type {string}
     * @memberof ReceiptDto
     */
    'user': string;
    /**
     * 
     * @type {ReceiptSource}
     * @memberof ReceiptDto
     */
    'source': ReceiptSource;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDto
     */
    'type': string;
    /**
     * 
     * @type {ReceiptDetail}
     * @memberof ReceiptDto
     */
    'detail': ReceiptDetail;
    /**
     * 
     * @type {ReceiptTransactionInfo}
     * @memberof ReceiptDto
     */
    'transactionInfo'?: ReceiptTransactionInfo;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDto
     */
    'status': ReceiptDtoStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDto
     */
    'updatedAt': string;
}

export const ReceiptDtoStatusEnum = {
    Pending: 'pending',
    Claimed: 'claimed',
    Granted: 'granted',
    Failed: 'failed',
    Refunded: 'refunded'
} as const;

export type ReceiptDtoStatusEnum = typeof ReceiptDtoStatusEnum[keyof typeof ReceiptDtoStatusEnum];


