/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReceiptDetail
 */
export interface ReceiptDetail {
    /**
     * 
     * @type {number}
     * @memberof ReceiptDetail
     */
    'amount': number;
    /**
     * 
     * @type {number}
     * @memberof ReceiptDetail
     */
    'decimals': number;
    /**
     * 
     * @type {string}
     * @memberof ReceiptDetail
     */
    'symbol': string;
}

