/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReceiptControllerGetReceipts200ResponsePagination
 */
export interface ReceiptControllerGetReceipts200ResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof ReceiptControllerGetReceipts200ResponsePagination
     */
    'totalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReceiptControllerGetReceipts200ResponsePagination
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReceiptControllerGetReceipts200ResponsePagination
     */
    'currentPage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReceiptControllerGetReceipts200ResponsePagination
     */
    'hasNextPage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReceiptControllerGetReceipts200ResponsePagination
     */
    'hasPrevPage'?: boolean;
}

