/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubUser } from './github-user';

/**
 * 
 * @export
 * @interface Report
 */
export interface Report {
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    '_id': string;
    /**
     * 
     * @type {object}
     * @memberof Report
     */
    'projectId': object;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'from': string;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'to': string;
    /**
     * 
     * @type {number}
     * @memberof Report
     */
    'issueCount': number;
    /**
     * 
     * @type {Array<GithubUser>}
     * @memberof Report
     */
    'users': Array<GithubUser>;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Report
     */
    'updatedAt': string;
}

