/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReputationDetailsDto
 */
export interface ReputationDetailsDto {
    /**
     * Number of tasks completed on time
     * @type {number}
     * @memberof ReputationDetailsDto
     */
    'completed': number;
    /**
     * Number of tasks completed after deadline
     * @type {number}
     * @memberof ReputationDetailsDto
     */
    'delayedCompleted': number;
    /**
     * Number of tasks abandoned before deadline
     * @type {number}
     * @memberof ReputationDetailsDto
     */
    'earlyAbandoned': number;
    /**
     * Number of tasks abandoned after deadline
     * @type {number}
     * @memberof ReputationDetailsDto
     */
    'delayedAbandoned': number;
}

