/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'githubId': number;
    /**
     * 
     * @type {object}
     * @memberof Task
     */
    'project': object;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'body': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'closedAt': string;
    /**
     * 
     * @type {object}
     * @memberof Task
     */
    'assignee': object;
    /**
     * 
     * @type {Array<string>}
     * @memberof Task
     */
    'assignees': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Task
     */
    'labels': Array<string>;
    /**
     * 
     * @type {object}
     * @memberof Task
     */
    'user': object;
    /**
     * 
     * @type {Array<string>}
     * @memberof Task
     */
    'labelsWithColor': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'htmlUrl': string;
    /**
     * 
     * @type {object}
     * @memberof Task
     */
    'namespace': object;
    /**
     * 
     * @type {object}
     * @memberof Task
     */
    'reward': object;
    /**
     * 
     * @type {boolean}
     * @memberof Task
     */
    'rewardGranted': boolean;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'level': string;
}

