/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskApply
 */
export interface TaskApply {
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    '_id': string;
    /**
     * 
     * @type {number}
     * @memberof TaskApply
     */
    'githubId': number;
    /**
     * 
     * @type {object}
     * @memberof TaskApply
     */
    'project': object;
    /**
     * 
     * @type {object}
     * @memberof TaskApply
     */
    'task': object;
    /**
     * 
     * @type {object}
     * @memberof TaskApply
     */
    'user': object;
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    'comment': string;
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    'htmlUrl': string;
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    'canceledAt': string;
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    'approvedAt': string;
    /**
     * 
     * @type {object}
     * @memberof TaskApply
     */
    'namespace': object;
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    'projectName': string;
    /**
     * 
     * @type {string}
     * @memberof TaskApply
     */
    'taskTitle': string;
}

