/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TaskApply } from './task-apply';
// May contain unused imports in some cases
// @ts-ignore
import type { TaskControllerGetTasks200ResponsePagination } from './task-controller-get-tasks200-response-pagination';

/**
 * 
 * @export
 * @interface TaskApplyControllerGetTaskApplies200Response
 */
export interface TaskApplyControllerGetTaskApplies200Response {
    /**
     * 
     * @type {TaskControllerGetTasks200ResponsePagination}
     * @memberof TaskApplyControllerGetTaskApplies200Response
     */
    'pagination'?: TaskControllerGetTasks200ResponsePagination;
    /**
     * 
     * @type {Array<TaskApply>}
     * @memberof TaskApplyControllerGetTaskApplies200Response
     */
    'data'?: Array<TaskApply>;
}

