/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Task } from './task';

/**
 * 
 * @export
 * @interface TaskControllerGetTasks200Response
 */
export interface TaskControllerGetTasks200Response {
    /**
     * 
     * @type {number}
     * @memberof TaskControllerGetTasks200Response
     */
    'totalCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskControllerGetTasks200Response
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskControllerGetTasks200Response
     */
    'currentPage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TaskControllerGetTasks200Response
     */
    'hasNextPage'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TaskControllerGetTasks200Response
     */
    'hasPrevPage'?: boolean;
    /**
     * 
     * @type {Array<Task>}
     * @memberof TaskControllerGetTasks200Response
     */
    'data'?: Array<Task>;
}

