/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GithubUser } from './github-user';
// May contain unused imports in some cases
// @ts-ignore
import type { LabelWithColorDto } from './label-with-color-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { Project } from './project';
// May contain unused imports in some cases
// @ts-ignore
import type { RewardDetail } from './reward-detail';

/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    '_id': string;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'githubId': number;
    /**
     * 
     * @type {Project}
     * @memberof Task
     */
    'project': Project;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'body': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'closedAt': string;
    /**
     * 
     * @type {GithubUser}
     * @memberof Task
     */
    'assignee': GithubUser;
    /**
     * 
     * @type {Array<GithubUser>}
     * @memberof Task
     */
    'assignees': Array<GithubUser>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Task
     */
    'labels': Array<string>;
    /**
     * 
     * @type {GithubUser}
     * @memberof Task
     */
    'user': GithubUser;
    /**
     * 
     * @type {Array<LabelWithColorDto>}
     * @memberof Task
     */
    'labelsWithColor': Array<LabelWithColorDto>;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'htmlUrl': string;
    /**
     * 
     * @type {object}
     * @memberof Task
     */
    'namespace': object;
    /**
     * 
     * @type {RewardDetail}
     * @memberof Task
     */
    'reward': RewardDetail;
    /**
     * 
     * @type {boolean}
     * @memberof Task
     */
    'rewardGranted': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Task
     */
    'rewardClaimed': boolean;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'level': string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'priority'?: TaskPriorityEnum;
    /**
     * 
     * @type {number}
     * @memberof Task
     */
    'storyPoints'?: number;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'due'?: string;
}

export const TaskPriorityEnum = {
    P0: 'p0',
    P1: 'p1',
    P2: 'p2'
} as const;

export type TaskPriorityEnum = typeof TaskPriorityEnum[keyof typeof TaskPriorityEnum];


