/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskProjectDto
 */
export interface TaskProjectDto {
    /**
     * 
     * @type {string}
     * @memberof TaskProjectDto
     */
    '_id': string;
    /**
     * 
     * @type {string}
     * @memberof TaskProjectDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TaskProjectDto
     */
    'htmlUrl': string;
}

