/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RewardDetail } from './reward-detail';

/**
 * 
 * @export
 * @interface UpdateTaskDto
 */
export interface UpdateTaskDto {
    /**
     * Task title
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'title'?: string;
    /**
     * Task reward details
     * @type {RewardDetail}
     * @memberof UpdateTaskDto
     */
    'reward'?: RewardDetail;
    /**
     * Task level
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'level'?: string;
    /**
     * Task priority (p0, p1, p2)
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'priority'?: UpdateTaskDtoPriorityEnum;
    /**
     * Story points for the task
     * @type {number}
     * @memberof UpdateTaskDto
     */
    'storyPoints'?: number;
    /**
     * Due date for the task
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'due'?: string;
}

export const UpdateTaskDtoPriorityEnum = {
    P0: 'p0',
    P1: 'p1',
    P2: 'p2'
} as const;

export type UpdateTaskDtoPriorityEnum = typeof UpdateTaskDtoPriorityEnum[keyof typeof UpdateTaskDtoPriorityEnum];


