/* tslint:disable */
/* eslint-disable */
/**
 * YouBet Task API
 * YouBet Task RESTful API 文档
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReputationDetailsDto } from './reputation-details-dto';

/**
 * 
 * @export
 * @interface UserReputationDto
 */
export interface UserReputationDto {
    /**
     * User reputation score (0-10)
     * @type {number}
     * @memberof UserReputationDto
     */
    'score': number;
    /**
     * Number of tasks used for reputation calculation
     * @type {number}
     * @memberof UserReputationDto
     */
    'taskCount': number;
    /**
     * Breakdown of task completion details
     * @type {ReputationDetailsDto}
     * @memberof UserReputationDto
     */
    'details': ReputationDetailsDto;
}

